export const FETCH_ASSESTS_START = "FETCH_ASSESTS_START";
export const FETCH_ASSESTS_SUCCESS = "FETCH_ASSESTS_SUCCESS";
export const ADD_NEW_SYMBOL = "ADD_NEW_SYMBOL";
export const ADD_NEW_SYMBOL_SUCCESS = "ADD_NEW_SYMBOL_SUCCESS";

export const EDIT_SYMBOL_START = "EDIT_SYMBOL_START";
export const EDIT_SYMBOL_DONE = "EDIT_SYMBOL_DONE";
export const EDIT_SYMBOL_CLEAR = "EDIT_SYMBOL_CLEAR";

export const DELETE_SYMBOL_START = "DELETE_SYMBOL_START";
export const DELETE_SYMBOL_DONE = "DELETE_SYMBOL_DONE";

export const API_ERROR = "API_ERROR";