export const FETCH_ASSESTS_START = "FETCH_ASSESTS_START";
export const FETCH_ASSESTS_SUCCESS = "FETCH_ASSESTS_SUCCESS";
export const ADD_NEW_SYMBOL = "ADD_NEW_SYMBOL";
export const ADD_NEW_SYMBOL_SUCCESS = "ADD_NEW_SYMBOL_SUCCESS";
export const API_ERROR = "API_ERROR";