// fetch forex deposits
export const FETCH_TRADING_ACCOUNTS_REQUESTED = "FETCH_TRADING_ACCOUNTS_REQUESTED";
export const FETCH_TRADING_ACCOUNTS_SUCCESS = "FETCH_TRADING_ACCOUNTS_SUCCESS";
export const FETCH_TRADING_ACCOUNTS_FAIL = "FETCH_TRADING_ACCOUNTS_FAIL";