
export const FETCH_ACCOUNT_TYPES_START = "FETCH_ACCOUNT_TYPES_START";
export const FETCH_ACCOUNT_TYPES_END = "FETCH_ACCOUNT_TYPES_END";

export const CREATE_TRADING_ACCOUNT_START = "CREATE_TRADING_ACCOUNT_START";
export const CREATE_TRADING_ACCOUNT_END = "CREATE_TRADING_ACCOUNT_END";
export const CREATE_TRADING_ACCOUNT_CLEAR = "CREATE_TRADING_ACCOUNT_CLEAR";

export const FETCH_TRADING_ACCOUNT_START = "FETCH_TRADING_ACCOUNT_START";
export const FETCH_TRADING_ACCOUNT_END = "FETCH_TRADING_ACCOUNT_END";
