export const FETCH_WALLET_START = "FETCH_WALLET_START";
export const FETCH_WALLET_SUCCESS = "FETCH_WALLET_SUCCESS";
export const CLEAR_WALLETS = "CLEAR_WALLETS";

// fetch client wallet details
export const FETCH_CLIENT_WALLET_REQUESTED = "FETCH_CLIENT_WALLET_REQUESTED";
export const FETCH_CLIENT_WALLET_SUCCESS = "FETCH_CLIENT_WALLET_SUCCESS";
export const FETCH_CLIENT_WALLET_FAIL = "FETCH_CLIENT_WALLET_FAIL";