
export const FETCH_USERS_START = "FETCH_USERS_START";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";

export const ADD_USERS_START = "ADD_USERS_START";
export const ADD_USERS_SUCCESS = "ADD_USERS_SUCCESS";
export const ADD_USERS_ERROR = "ADD_USERS_ERROR";
export const ADD_USER_CLEAR = "ADD_USER_CLEAR";

export const FETCH_USERS_ROLES_START = "FETCH_USERS_ROLES_START";
export const FETCH_USERS_ROLES_SUCCESS = "FETCH_USERS_ROLES_SUCCESS";
export const FETCH_USERS_ROLES_ERROR = "FETCH_USERS_ROLES_ERROR";
 
export const EDIT_USERS_PASS_START = "EDIT_USERS_PASS_START";
export const EDIT_USERS_START = "EDIT_USERS_START";
export const EDIT_USERS_DONE = "EDIT_USERS_DONE";
export const EDIT_USERS_ERROR = "EDIT_USERS_ERROR";
export const EDIT_USER_CLEAR = "EDIT_USER_CLEAR";

export const DELETE_USERS_START = "DELETE_USERS_START";
export const DELETE_USERS_DONE =  "DELETE_USERS_DONE";
