export const FETCH_FEE_GROUPS_START = "FETCH_FEE_GROUPS_START";
export const FETCH_FEE_GROUPS_SUCCESS = "FETCH_FEE_GROUPS_SUCCESS";
export const API_ERROR = "API_ERROR";
export const ADD_FEES_GROUPS_START = "ADD_FEES_GROUPS_START";
export const ADD_FEES_GROUPS_SUCCESS = "ADD_FEES_GROUPS_SUCCESS";