export const FETCH_FOREX_GATEWAYS_START = "FETCH_FOREX_GATEWAYS_START";
export const FETCH_FOREX_GATEWAYS_SUCCESS = "FETCH_FOREX_GATEWAYS_SUCCESS";
export const FETCH_WITHDRAWALS_FOREX_GATEWAYS_START = "FETCH_WITHDRAWALS_FOREX_GATEWAYS_START";
export const FETCH_WITHDRAWALS_FOREX_GATEWAYS_SUCCESS = "FETCH_WITHDRAWALS_FOREX_GATEWAYS_SUCCESS";