export const FETCH_CLIENTS_START = "FETCH_CLIENTS_START";
export const FETCH_CLIENTS_SUCCESS = "FETCH_CLIENTS_SUCCESS";
export const ADD_NEW_CLIENT = "ADD_NEW_CLIENT";
export const ADD_NEW_CLIENT_SUCCESS = "ADD_NEW_CLIENT_SUCCESS";
export const API_ERROR = "API_ERROR";

// fetch client details
export const FETCH_CLIENT_DETAILS_REQUESTED = "FETCH_CLIENT_DETAILS_REQUESTED";
export const FETCH_CLIENT_DETAILS_SUCCESS = "FETCH_CLIENT_DETAILS_SUCCESS";
export const FETCH_CLIENT_DETAILS_FAIL = "FETCH_CLIENT_DETAILS_FAIL";
export const FETCH_CLIENT_DETAILS_CLEAR = "FETCH_CLIENT_DETAILS_CLEAR";

// fetch client bank details
export const FETCH_CLIENT_BANK_ACCOUNT_REQUESTED = "FETCH_CLIENT_BANK_ACCOUNT_REQUESTED";
export const FETCH_CLIENT_BANK_ACCOUNT_SUCCESS = "FETCH_CLIENT_BANK_ACCOUNT_SUCCESS";
export const FETCH_CLIENT_BANK_ACCOUNT_FAIL = "FETCH_CLIENT_BANK_ACCOUNT_FAIL";

// fetch client wallet details
export const FETCH_CLIENT_WALLET_REQUESTED = "FETCH_CLIENT_WALLET_REQUESTED";
export const FETCH_CLIENT_WALLET_SUCCESS = "FETCH_CLIENT_WALLET_SUCCESS";
export const FETCH_CLIENT_WALLET_FAIL = "FETCH_CLIENT_WALLET_FAIL";

// fetch client transactions 
export const FETCH_CLIENT_TRANSACTIONS_REQUESTED = "FETCH_CLIENT_TRANSACTIONS_REQUESTED";
export const FETCH_CLIENT_TRANSACTIONS_SUCCESS = "FETCH_CLIENT_TRANSACTIONS_SUCCESS";
export const FETCH_CLIENT_TRANSACTIONS_FAIL = "FETCH_CLIENT_TRANSACTIONS_FAIL";

// update client details 
export const EDIT_CLIENT_DETAILS_REQUESTED = "EDIT_CLIENT_DETAILS_REQUESTED";
export const EDIT_CLIENT_DETAILS_SUCCESS = "EDIT_CLIENT_DETAILS_SUCCESS";
export const EDIT_CLIENT_DETAILS_FAIL = "EDIT_CLIENT_DETAILS_FAIL";
export const EDIT_CLIENT_DETAILS_CLEAR = "EDIT_CLIENT_DETAILS_CLEAR";

// add bank account
export const ADD_BANK_ACCOUNT_REQUESTED = "ADD_BANK_ACCOUNT_REQUESTED";
export const ADD_BANK_ACCOUNT_SUCCESS = "ADD_BANK_ACCOUNT_SUCCESS";
export const ADD_BANK_ACCOUNT_FAIL = "ADD_BANK_ACCOUNT_FAIL";
export const ADD_BANK_ACCOUNT_CLEAR = "ADD_BANK_ACCOUNT_CLEAR";

// delete bank account
export const DELETE_BANK_ACCOUNT_REQUESTED = "DELETE_BANK_ACCOUNT_REQUESTED";
export const DELETE_BANK_ACCOUNT_SUCCESS = "DELETE_BANK_ACCOUNT_SUCCESS";
export const DELETE_BANK_ACCOUNT_FAIL = "DELETE_BANK_ACCOUNT_FAIL";

// edit bank account
export const EDIT_BANK_ACCOUNT_REQUESTED = "EDIT_BANK_ACCOUNT_REQUESTED";
export const EDIT_BANK_ACCOUNT_SUCCESS = "EDIT_BANK_ACCOUNT_SUCCESS";
export const EDIT_BANK_ACCOUNT_FAIL = "EDIT_BANK_ACCOUNT_FAIL";
export const EDIT_BANK_ACCOUNT_CLEAR = "EDIT_BANK_ACCOUNT_CLEAR";