// fetch
// the REQUESTED action type is just a part of a pattern in redux saga 
// it just means that an action was called but didn't return a value yet
export const FETCH_SYSTEM_EMAILS_REQUESTED = "FETCH_SYSTEM_EMAILS_REQUESTED";
export const FETCH_SYSTEM_EMAILS_SUCCESS = "FETCH_SYSTEM_EMAILS_SUCCESS";
export const FETCH_SYSTEM_EMAILS_FAIL = "FETCH_SYSTEM_EMAILS_FAIL";

// add
export const ADD_SYSTEM_EMAIL_REQUESTED = "ADD_SYSTEM_EMAIL_REQUESTED";
export const ADD_SYSTEM_EMAIL_SUCCESS = "ADD_SYSTEM_EMAIL_SUCCESS";
export const ADD_SYSTEM_EMAIL_FAIL = "ADD_SYSTEM_EMAIL_FAIL";

// delete
export const DELETE_SYSTEM_EMAIL_REQUESTED = "DELETE_SYSTEM_EMAIL_REQUESTED";
export const DELETE_SYSTEM_EMAIL_SUCCESS = "DELETE_SYSTEM_EMAIL_SUCCESS";
export const DELETE_SYSTEM_EMAIL_FAIL = "DELETE_SYSTEM_EMAIL_FAIL";

// edit 
export const EDIT_SYSTEM_EMAIL_REQUESTED = "EDIT_SYSTEM_EMAIL_REQUESTED";
export const EDIT_SYSTEM_EMAIL_SUCCESS = "EDIT_SYSTEM_EMAIL_SUCCESS";
export const EDIT_SYSTEM_EMAIL_FAIL = "EDIT_SYSTEM_EMAIL_FAIL";
