export const FETCH_LEADS = "FETCH_LEADS";
export const FETCH_LEADS_SUCCESS = "FETCH_LEADS_SUCCESS";
export const API_ERROR = "API_ERROR";
export const ADD_NEW_LEAD = "ADD_NEW_LEAD";
export const ADD_NEW_LEAD_SUCCESS = "ADD_NEW_LEAD_SUCCESS";