export const FETCH_IB_REQUESTS_START = "FETCH_IB_REQUESTS_START";
export const FETCH_IB_REQUESTS_SUCCESS = "FETCH_IB_REQUESTS_SUCCESS";
export const FETCH_IB_REQUESTS_ERROR = "FETCH_IB_REQUESTS_ERROR";


export const IB_REQUEST_APPROVE_START = "IB_REQUEST_APPROVE_START";
export const IB_REQUEST_STATUS_CHANGE_TO_APPROVE_SUCCESS = "IB_REQUEST_STATUS_CHANGE_TO_APPROVE_SUCCESS";


export const IB_REQUEST_REJECT_START = "IB_REQUEST_REJECT_START";
export const IB_REQUEST_STATUS_CHANGE_TO_REJECT_SUCCESS = "IB_REQUEST_STATUS_CHANGE_TO_REJECT_SUCCESS";

//leverage requests
export const FETCH_LEVERAGE_REQUESTS_START = "FETCH_LEVERAGE_REQUESTS_START";
export const FETCH_LEVERAGE_REQUESTS_SUCCESS = "FETCH_LEVERAGE_REQUESTS_SUCCESS";
export const FETCH_LEVERAGE_REQUESTS_ERROR = "FETCH_LEVERAGE_REQUESTS_ERROR";


export const LEVERAGE_REQUEST_APPROVE_START = "LEVERAGE_REQUEST_APPROVE_START";
export const LEVERAGE_REQUEST_STATUS_CHANGE_TO_APPROVE_SUCCESS = "LEVERAGE_REQUEST_STATUS_CHANGE_TO_APPROVE_SUCCESS";


export const LEVERAGE_REQUEST_REJECT_START = "LEVERAGE_REQUEST_REJECT_START";
export const LEVERAGE_REQUEST_STATUS_CHANGE_TO_REJECT_SUCCESS = "LEVERAGE_REQUEST_STATUS_CHANGE_TO_REJECT_SUCCESS";
