
export const FETCH_CUSTOMERS_COUNTRIES_START = "FETCH_CUSTOMERS_COUNTRIES_START";
export const FETCH_CUSTOMERS_COUNTRIES_END = "FETCH_CUSTOMERS_COUNTRIES_END";

export const FETCH_CUSTOMERS_STATS_START = "FETCH_CUSTOMERS_STATS_START";
export const FETCH_CUSTOMERS_STATS_END = "FETCH_CUSTOMERS_STATS_END";
