// fetch
// the REQUESTED action type is just a part of a pattern in redux saga 
// it just means that an action was called but didn't return a value yet
export const FETCH_EMAIL_TEMPLATES_REQUESTED = "FETCH_EMAIL_TEMPLATES_REQUESTED";
export const FETCH_EMAIL_TEMPLATES_SUCCESS = "FETCH_EMAIL_TEMPLATES_SUCCESS";
export const FETCH_EMAIL_TEMPLATES_FAIL = "FETCH_EMAIL_TEMPLATES_FAIL";

// add
export const ADD_EMAIL_TEMPLATE_REQUESTED = "ADD_EMAIL_TEMPLATE_REQUESTED";
export const ADD_EMAIL_TEMPLATE_SUCCESS = "ADD_EMAIL_TEMPLATE_SUCCESS";
export const ADD_EMAIL_TEMPLATE_FAIL = "ADD_EMAIL_TEMPLATE_FAIL";

// delete
export const DELETE_EMAIL_TEMPLATE_REQUESTED = "DELETE_EMAIL_TEMPLATE_REQUESTED";
export const DELETE_EMAIL_TEMPLATE_SUCCESS = "DELETE_EMAIL_TEMPLATE_SUCCESS";
export const DELETE_EMAIL_TEMPLATE_FAIL = "DELETE_EMAIL_TEMPLATE_FAIL";

// edit 
export const EDIT_EMAIL_TEMPLATE_REQUESTED = "EDIT_EMAIL_TEMPLATE_REQUESTED";
export const EDIT_EMAIL_TEMPLATE_SUCCESS = "EDIT_EMAIL_TEMPLATE_SUCCESS";
export const EDIT_EMAIL_TEMPLATE_FAIL = "EDIT_EMAIL_TEMPLATE_FAIL";
