export const PRODUCTS_START = "PRODUCTS_START";
export const PRODUCTS_SUCCESSFUL = "PRODUCTS_SUCCESSFUL";
export const ADD_PRODUCT_START = "ADD_PRODUCT_START";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_START = "EDIT_PRODUCT_START";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const MODAL_CLEAR = "MODAL_CLEAR";
export const API_ERROR = "API_ERROR";
