export const FETCH_TEAMS_START = "FETCH_TEAMS_START";
export const FETCH_TEAMS_SUCCESSFUL = "FETCH_TEAMS_SUCCESSFUL";
export const ADD_TEAMS_START = "ADD_TEAMS_START";
export const ADD_TEAMS_SUCCESSFUL = "ADD_TEAMS_SUCCESSFUL";
export const MODAL_CLEAR = "MODAL_CLEAR";
export const API_ERROR = "API_ERROR";
